<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
		'key'                   => 'group_5ea47e4201029',
		'title'                 => 'Element Creator',
		'fields'                => array(
		array(
			'key'               => 'field_5ea47f078e3d7',
			'label'             => esc_attr__( 'Attributes', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_5ea7292ab291b',
			'label'             => esc_attr__( 'Element Icon Class', 'elegant-elements' ),
			'name'              => 'element_icon_class',
			'type'              => 'text',
			'instructions'      => esc_attr__( 'Use the FontAwesome icon class or Dashicons icon class for the element icon.', 'elegant-elements' ),
			'required'          => 1,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => 'fa-cog fas',
			'placeholder'       => 'fa-cog fas',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		),
		array(
			'key'               => 'field_5ea710e7e57b9',
			'label'             => esc_attr__( 'WordPress Editor Field', 'elegant-elements' ),
			'name'              => 'wp_editor_field',
			'type'              => 'group',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'layout'            => 'block',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea71110e57ba',
					'label'             => esc_attr__( 'Allow WordPress Editor Field?', 'elegant-elements' ),
					'name'              => 'wp_editor_field',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 1,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_5ea71152e57bb',
					'label'             => esc_attr__( 'Heading', 'elegant-elements' ),
					'name'              => 'heading',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5ea71110e57ba',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ea711ace57bc',
					'label'             => esc_attr__( 'Description', 'elegant-elements' ),
					'name'              => 'description',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5ea71110e57ba',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ea71767b0d9d',
					'label'             => esc_attr__( 'Settings Group Name', 'elegant-elements' ),
					'name'              => 'settings_group',
					'type'              => 'text',
					'instructions'      => esc_attr__( 'If you want to display this field in a separate tab as a group of settings, enter the group name.', 'elegant-elements' ),
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5ea71110e57ba',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
		),
		array(
			'key'               => 'field_5ea47f5e8e3d9',
			'label'             => esc_attr__( 'Attributes', 'elegant-elements' ),
			'name'              => 'attributes',
			'type'              => 'group',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'layout'            => 'block',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea49cc833267',
					'label'             => esc_attr__( 'Attribute', 'elegant-elements' ),
					'name'              => 'attribute',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => 'hide-field-label',
						'id'    => '',
					),
					'collapsed'         => 'field_5ea49d4933268',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'row',
					'button_label'      => '+ Attribute',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5ea49d4933268',
							'label'             => esc_attr__( 'Heading', 'elegant-elements' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => esc_attr__( 'Text to be displayed for the field when you edit the element in the builder.', 'elegant-elements' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5ea5d7cf2a8fe',
							'label'             => esc_attr__( 'Param Name', 'elegant-elements' ),
							'name'              => 'param_name',
							'type'              => 'text',
							'instructions'      => esc_attr__( 'Use small letters with underscores ( _ ) to separate words. Eg. button_title', 'elegant-elements' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'param_name',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5ea6a841a9750',
							'label'             => esc_attr__( 'Default Value', 'elegant-elements' ),
							'name'              => 'default_value',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5ea4a60147bd4',
							'label'             => esc_attr__( 'Description', 'elegant-elements' ),
							'name'              => 'description',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5ea49d6233269',
							'label'             => esc_attr__( 'Setting Type', 'elegant-elements' ),
							'name'              => 'element_settings_type',
							'type'              => 'select',
							'instructions'      => esc_attr__( 'Choose the setting type for this attribute field.', 'elegant-elements' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'textfield'           => esc_attr__( 'Text Field', 'elegant-elements' ),
								'textarea'            => esc_attr__( 'Textarea', 'elegant-elements' ),
								'range'               => esc_attr__( 'Range', 'elegant-elements' ),
								'colorpicker'         => esc_attr__( 'Color Picker', 'elegant-elements' ),
								'colorpickeralpha'    => esc_attr__( 'Color Picker - RGBA', 'elegant-elements' ),
								'select'              => esc_attr__( 'Select Field', 'elegant-elements' ),
								'checkbox_button_set' => esc_attr__( 'Checkbox Button Set', 'elegant-elements' ),
								'radio_button_set'    => esc_attr__( 'Radio Button Set', 'elegant-elements' ),
								'upload'              => esc_attr__( 'Image Upload', 'elegant-elements' ),
								'uploadfile'          => esc_attr__( 'File Upload', 'elegant-elements' ),
								'iconpicker'          => esc_attr__( 'Icon Picker', 'elegant-elements' ),
								'multiple_select'     => esc_attr__( 'Multiple Select', 'elegant-elements' ),
								'link_selector'       => esc_attr__( 'Link Selector', 'elegant-elements' ),
								'date_time_picker'    => esc_attr__( 'Date Time Picker', 'elegant-elements' ),
								'padding'             => esc_attr__( 'Padding', 'elegant-elements' ),
								'margin'              => esc_attr__( 'Margin', 'elegant-elements' ),
							),
							'default_value'     => array(
								0 => 'textfield',
							),
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 1,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_5ea4a736ef2b7',
							'label'             => esc_attr__( 'Options', 'elegant-elements' ),
							'name'              => 'options',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5ea49d6233269',
										'operator' => '==',
										'value'    => 'checkbox_button_set',
									),
								),
								array(
									array(
										'field'    => 'field_5ea49d6233269',
										'operator' => '==',
										'value'    => 'radio_button_set',
									),
								),
								array(
									array(
										'field'    => 'field_5ea49d6233269',
										'operator' => '==',
										'value'    => 'select',
									),
								),
								array(
									array(
										'field'    => 'field_5ea49d6233269',
										'operator' => '==',
										'value'    => 'multiple_select',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => 'field_5ea4a763ef2b8',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => esc_attr__( '+ Option', 'elegant-elements' ),
							'sub_fields'        => array(
								array(
									'key'               => 'field_5ea4a763ef2b8',
									'label'             => esc_attr__( 'Option Name', 'elegant-elements' ),
									'name'              => 'option_name',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5ea4a78fef2b9',
									'label'             => esc_attr__( 'Option Value', 'elegant-elements' ),
									'name'              => 'option_value',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_5ea6fbc777a67',
							'label'             => esc_attr__( 'Range Values', 'elegant-elements' ),
							'name'              => 'range_values',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5ea49d6233269',
										'operator' => '==',
										'value'    => 'range',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_5ea6fbde77a68',
									'label'             => esc_attr__( 'Minimun', 'elegant-elements' ),
									'name'              => 'min',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'min'               => '',
									'max'               => '',
									'step'              => '',
								),
								array(
									'key'               => 'field_5ea6fc0777a69',
									'label'             => esc_attr__( 'Maximum', 'elegant-elements' ),
									'name'              => 'max',
									'type'              => 'number',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'min'               => '',
									'max'               => '',
									'step'              => '',
								),
							),
						),
						array(
							'key'               => 'field_5ea4a6ba47bd5',
							'label'             => esc_attr__( 'Settings Group', 'elegant-elements' ),
							'name'              => 'settings_group',
							'type'              => 'text',
							'instructions'      => esc_attr__( 'If you want to display this field in a separate tab as a group of settings, enter the group name.', 'elegant-elements' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
		),
		array(
			'key'               => 'field_5ea47fb90d853',
			'label'             => esc_attr__( 'HTML', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_5ea47fc50d854',
			'label'             => esc_attr__( 'HTML', 'elegant-elements' ),
			'name'              => 'element_html',
			'type'              => 'group',
			'instructions'      => '',
			'required'          => 1,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'hide-field-label',
				'id'    => '',
			),
			'layout'            => 'block',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea4abba3e0ad',
					'label'             => esc_attr__( 'Editor', 'elegant-elements' ),
					'name'              => 'editor',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '75',
						'class' => '',
						'id'    => 'element-html-editor',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_5ea4abd33e0ae',
					'label'             => esc_attr__( 'Variables', 'elegant-elements' ),
					'name'              => 'variables',
					'type'              => 'element_creator_template_tags',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
				),
			),
		),
		array(
			'key'               => 'field_5ea4aa88165df',
			'label'             => esc_attr__( 'CSS', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_5ea4aa95165e0',
			'label'             => esc_attr__( 'CSS', 'elegant-elements' ),
			'name'              => 'element_css',
			'type'              => 'group',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'hide-field-label',
				'id'    => '',
			),
			'layout'            => 'block',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea574f285bd7',
					'label'             => esc_attr__( 'Editor', 'elegant-elements' ),
					'name'              => 'editor',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '75',
						'class' => '',
						'id'    => 'element-css-editor',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_5ea5750a85bd8',
					'label'             => esc_attr__( 'Variables', 'elegant-elements' ),
					'name'              => 'variables',
					'type'              => 'element_creator_template_tags',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
				),
			),
		),
		array(
			'key'               => 'field_5ea4ab8a3e0ac',
			'label'             => esc_attr__( 'JavaScript', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_5ea4ab4016628',
			'label'             => esc_attr__( 'JavaScript', 'elegant-elements' ),
			'name'              => 'element_js',
			'type'              => 'group',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'hide-field-label',
				'id'    => '',
			),
			'layout'            => 'block',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea4ab5716629',
					'label'             => esc_attr__( 'Editor', 'elegant-elements' ),
					'name'              => 'editor',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '75',
						'class' => '',
						'id'    => 'element-js-editor',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_5ea4ab631662a',
					'label'             => esc_attr__( 'Variables', 'elegant-elements' ),
					'name'              => 'variables',
					'type'              => 'element_creator_template_tags',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
				),
			),
		),
		array(
			'key'               => 'field_5ea73a3159e3a',
			'label'             => esc_attr__( 'JS / CSS Files', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'tab',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'placement'         => 'top',
			'endpoint'          => 0,
		),
		array(
			'key'               => 'field_5ea73bfadd1ee',
			'label'             => esc_attr__( 'Info', 'elegant-elements' ),
			'name'              => '',
			'type'              => 'message',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => 'hide-field-label',
				'id'    => '',
			),
			'message'           => esc_attr__( 'Files uploaded here will be auto enqueued on the frontend where the element is used. If element is not used anywhere, no files will be enqueued.', 'elegant-elements' ),
			'new_lines'         => 'wpautop',
			'esc_html'          => 0,
		),
		array(
			'key'               => 'field_5ea73fa06ffe8',
			'label'             => esc_attr__( 'CSS Files', 'elegant-elements' ),
			'name'              => 'css_files',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => '',
			'min'               => 0,
			'max'               => 0,
			'layout'            => 'table',
			'button_label'      => '',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea73faf6ffe9',
					'label'             => esc_attr__( 'File Name', 'elegant-elements' ),
					'name'              => 'file_name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ea73fb66ffea',
					'label'             => esc_attr__( 'Upload File', 'elegant-elements' ),
					'name'              => 'upload_file',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => '.css,.woff,.ttf',
				),
			),
		),
		array(
			'key'               => 'field_5ea73ab059e3d',
			'label'             => esc_attr__( 'JavaScript Files', 'elegant-elements' ),
			'name'              => 'javascript_files',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => '',
			'min'               => 0,
			'max'               => 0,
			'layout'            => 'table',
			'button_label'      => '',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5ea73ee1331e8',
					'label'             => esc_attr__( 'File Name', 'elegant-elements' ),
					'name'              => 'file_name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ea73fff0eac9',
					'label'             => esc_attr__( 'Upload File', 'elegant-elements' ),
					'name'              => 'upload_file',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => '.js',
				),
			),
		),
		),
		'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'element_creator',
			),
		),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'seamless',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		)
	);

endif;
